// REFETCH INTERVAL
export const REFETCH_INTERVAL_IN_MS = 20000;

// QUERY KEYS
export const GET_ALL_CHARTS = "GET_ALL_CHARTS";
export const GET_CHART_CONFIG_QUERY_KEY = "GET_CHART_CONFIG_QUERY_KEY";
export const CREATE_CHART_QUERY_KEY = "CREATE_CHART_QUERY_KEY";
export const UPDATE_CHART_QUERY_KEY = "UPDATE_CHART_QUERY_KEY";

export const CONTRACT_INSTRUCTION_QUERY_KEY = "CONTRACT_INSTRUCTION_QUERY_KEY";
