// REFETCH INTERVAL
export const REFETCH_INTERVAL_IN_MS = 20000;

// QUERY KEYS
export const TRADING_PAIR_QUERY_KEY = "TRADING_PAIRS";
export const TRADING_PAIR_INFO_QUERY_KEY = "TRADING_PAIR_INFO";
export const TRANSACTIONS_QUERY_KEY = "TRANSACTIONS";

// REQUEST LIMIT
export const TRANSACTIONS_FETCH_LIMIT = 25;
